"""Generate the device headers that depend on the trained tokenizer.

  firmware/generated/bpe.h      encode direction: byte seeds + merge table, so
                                the device tokenizes typed text itself rather
                                than having prompt ids baked in at build time.
  firmware/generated/symbols.h  reserved token ids -- which id is <set>, which
                                is <pin>, which ten are the digits.

symbols.h is what lets command.h read a generation without a string table. The
ids are assigned by prepare.py's `reserved_symbols()` order and change whenever
the tokenizer is retrained, so these headers and data/bpe.json are a matched
pair; regenerate both together or the device will parse one grammar with
another's numbering and produce confident nonsense.

    uv run python src/gen_assets.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from tokenizers import Tokenizer

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "data"))

import frames      # noqa: E402
import prepare     # noqa: E402

OUT = ROOT / "firmware" / "generated"


def bytes_to_unicode() -> dict[int, str]:
    """GPT-2's byte <-> printable-codepoint map, as used by ByteLevel.

    Reproduced here rather than imported because the C encoder needs the exact
    seed token for every one of the 256 byte values, including the ones that map
    to codepoints above 0xFF.
    """
    bs = (list(range(ord("!"), ord("~") + 1))
          + list(range(ord("\xa1"), ord("\xac") + 1))
          + list(range(ord("\xae"), ord("\xff") + 1)))
    cs = bs[:]
    n = 0
    for b in range(256):
        if b not in bs:
            bs.append(b)
            cs.append(256 + n)
            n += 1
    return {b: chr(c) for b, c in zip(bs, cs)}


def rows(vals, per_line, fmt=str) -> str:
    out = []
    for i in range(0, len(vals), per_line):
        out.append("  " + ",".join(fmt(v) for v in vals[i:i + per_line]) + ",")
    return "\n".join(out)


def write_bpe(tok: Tokenizer, raw: dict) -> None:
    vocab, merges = raw["model"]["vocab"], raw["model"]["merges"]
    b2u = bytes_to_unicode()

    byte_tok = []
    for b in range(256):
        ch = b2u[b]
        if ch not in vocab:
            raise SystemExit(f"byte {b} -> {ch!r} missing from vocab")
        byte_tok.append(vocab[ch])

    entries = []
    for rank, pair in enumerate(merges):
        a, b = pair if isinstance(pair, (list, tuple)) else pair.split(" ", 1)
        merged = a + b
        if a not in vocab or b not in vocab or merged not in vocab:
            continue                      # merge whose product was pruned
        entries.append(((vocab[a] << 16) | vocab[b], rank, vocab[merged]))
    entries.sort(key=lambda e: e[0])

    # Decode direction, for the one slot whose content is text: a copied name.
    # The bytes are un-mapped here rather than on device because ByteLevel's
    # byte<->codepoint map sends 0x20 to U+0120, so a token string is not its
    # own bytes and a C decoder would have to carry the inverse table and a
    # UTF-8 reader. Doing it at build time makes device-side decode a memcpy.
    u2b = {ch: b for b, ch in b2u.items()}
    n_vocab = tok.get_vocab_size()
    id_to_str = {i: s for s, i in vocab.items()}
    blob: list[int] = []
    off: list[int] = [0]
    for i in range(n_vocab):
        s = id_to_str.get(i, "")
        # A token whose string leaves the byte alphabet cannot be a name
        # fragment; emitting it as empty keeps offsets aligned and lets the
        # parser reject it by id, which is a clearer failure than mojibake.
        blob.extend(u2b[c] for c in s if c in u2b)
        off.append(len(blob))

    with (OUT / "bpe.h").open("w") as f:
        f.write("// Generated by src/gen_assets.py -- BPE encode/decode tables.\n"
                "// Sorted by pair key so the device can binary-search merges.\n"
                "// Fixed-width types matter: on Xtensa `uint32_t` is `long\n"
                "// unsigned int`, so plain `unsigned int` arrays fail to bind\n"
                "// to the Bpe struct.\n"
                "#ifndef BPE_H\n#define BPE_H\n#include <stdint.h>\n\n")
        f.write(f"#define BPE_N_PAIRS {len(entries)}\n")
        f.write(f"#define BPE_VOCAB {n_vocab}\n")
        f.write(f"#define BPE_N_TOK_BYTES {len(blob)}\n\n")
        f.write("static const uint16_t BPE_BYTE_TOK[256] = {\n")
        f.write(rows(byte_tok, 16))
        f.write("\n};\n\nstatic const uint32_t BPE_PAIR_KEY[BPE_N_PAIRS] = {\n")
        f.write(rows([e[0] for e in entries], 10, lambda v: f"{v}u"))
        f.write("\n};\n\nstatic const uint16_t BPE_PAIR_RANK[BPE_N_PAIRS] = {\n")
        f.write(rows([e[1] for e in entries], 16))
        f.write("\n};\n\nstatic const uint16_t BPE_PAIR_NEW[BPE_N_PAIRS] = {\n")
        f.write(rows([e[2] for e in entries], 16))
        f.write("\n};\n\n"
                "// id -> its raw bytes, as a flat blob indexed by BPE_TOK_OFF.\n"
                "// BPE_TOK_OFF has BPE_VOCAB+1 entries, so a token's length is\n"
                "// off[id+1]-off[id] and the last id needs no special case.\n")
        f.write("static const uint16_t BPE_TOK_OFF[BPE_VOCAB + 1] = {\n")
        f.write(rows(off, 16))
        f.write("\n};\n\nstatic const uint8_t BPE_TOK_BYTES[BPE_N_TOK_BYTES] = {\n")
        f.write(rows(blob, 20))
        f.write("\n};\n\n"
                "// Every Bpe is built from this, so adding a table cannot\n"
                "// leave one caller initialising the old set of fields --\n"
                "// which would bind a decode pointer to whatever followed.\n"
                "#define BPE_INIT { BPE_BYTE_TOK, BPE_PAIR_KEY, BPE_PAIR_RANK, \\\n"
                "                   BPE_PAIR_NEW, BPE_N_PAIRS, BPE_TOK_OFF, \\\n"
                "                   BPE_TOK_BYTES, BPE_VOCAB }\n\n#endif\n")

    kb = (len(entries) * 8 + len(blob) + 2 * len(off) + 512) / 1024
    print(f"wrote {OUT / 'bpe.h'}: {len(entries)} merges, "
          f"{len(blob)} decode bytes, ~{kb:.0f} KB")


def write_symbols(tok: Tokenizer, meta: dict) -> None:
    def tid(s: str) -> int:
        i = tok.token_to_id(s)
        if i is None:
            raise SystemExit(f"symbol {s!r} is not in the tokenizer")
        return i

    named = [
        ("PAD", prepare.PAD), ("GO", prepare.GO), ("END", frames.S_END),
        ("PIN", frames.S_PIN), ("ALL", frames.S_ALL),
        ("NAME", frames.S_NAME), ("NEND", frames.S_NEND),
        ("INT", frames.S_INT), ("CNT", frames.S_CNT),
    ]
    named += [(a.value.upper(), frames.ACTION_SYM[a]) for a in frames.Action]
    named += [(l.value.upper(), frames.LEVEL_SYM[l]) for l in frames.Level]

    digits = [tid(str(d)) for d in range(10)]

    # SYM_RESERVED_N is only meaningful if the reserved ids really are the first
    # N. The trainer is given them first so they are, but that is a property of
    # someone else's library and it is checked rather than trusted -- if it ever
    # stopped holding, the device would silently accept markers inside a name.
    res_ids = sorted(tid(s) for s in prepare.reserved_symbols())
    if res_ids != list(range(len(res_ids))):
        raise SystemExit(f"reserved ids are not contiguous from 0: {res_ids}")

    with (OUT / "symbols.h").open("w") as f:
        f.write("// Generated by src/gen_assets.py -- reserved token ids.\n"
                "// Regenerate with data/bpe.json; the two are a matched pair.\n"
                "#ifndef SYMBOLS_H\n#define SYMBOLS_H\n#include <stdint.h>\n\n")
        f.write(f"#define SYM_VOCAB {tok.get_vocab_size()}\n")
        f.write(f"#define SYM_SEQ_LEN {meta['seq_len']}\n")
        # Reserved ids occupy [0, SYM_RESERVED_N) contiguously because
        # prepare.reserved_symbols() is handed to the trainer first. That is
        # what makes "is this id a marker?" a comparison instead of a lookup,
        # and it is how command.h rejects a name span that swallowed one.
        f.write(f"#define SYM_RESERVED_N {len(prepare.reserved_symbols())}\n")
        f.write(f"#define SYM_MAX_NAME {frames.MAX_NAME_CHARS}\n\n")
        for name, s in named:
            f.write(f"#define SYM_{name:<9} {tid(s):<5} // {s}\n")
        f.write("\n// Digit tokens, index == value. Pin numbers, intervals and\n"
                "// counts are all emitted as runs of these.\n")
        f.write("static const uint16_t SYM_DIGIT[10] = {\n")
        f.write(rows(digits, 10))
        f.write("\n};\n\n"
                "// -1 when the id is not a digit.\n"
                "static inline int sym_digit_value(int id) {\n"
                "  for (int i = 0; i < 10; i++) if (SYM_DIGIT[i] == id) return i;\n"
                "  return -1;\n}\n\n#endif\n")

    print(f"wrote {OUT / 'symbols.h'}: {len(named)} symbols + 10 digits")
    print(f"  go={meta['go']} end={tid(frames.S_END)} pin={tid(frames.S_PIN)} "
          f"digits={digits}")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    tok = Tokenizer.from_file(str(ROOT / "data" / "bpe.json"))
    meta = json.loads((ROOT / "data" / "meta.json").read_text())
    raw = json.loads((ROOT / "data" / "bpe.json").read_text())

    write_bpe(tok, raw)
    write_symbols(tok, meta)

    print("\nCheck the device encoder against the training tokenizer with:\n"
          "  cc -O3 -o /tmp/tok_test firmware/host_verify/tok_test.c\n"
          "  uv run python src/tok_check.py")


if __name__ == "__main__":
    main()
